--- #YAML:1.0
name:               Glib-Object-Introspection
version:            0.006
abstract:           Dynamically create Perl language bindings
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::Depends:    0.3
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1
    Glib:                 1.24
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Depends:    0.3
    ExtUtils::PkgConfig:  1
    Glib:                 1.24
no_index:
    directory:
        - t
        - inc
    file:
        - GObjectIntrospection.xs
    package:
        - MY
        - Glib::Object::Introspection::_FuncWrapper
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
